import 'dart:io';
import 'package:path/path.dart' as path;

/// Generator for BuildContext extension
class ExtensionGenerator {
  /// Generate extension file content as String (shared by CLI and builder).
  String generateContent(String className) {
    final buffer = StringBuffer();
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by Excel Translator');
    buffer.writeln();
    buffer.writeln('// Uncomment the lines below to enable BuildContext extension');
    buffer.writeln('// This provides easy access like: context.loc.localizations.hello');
    buffer.writeln('//');
    buffer.writeln("// import 'package:flutter/material.dart';");
    buffer.writeln("// import 'generated_localizations.dart';");
    buffer.writeln('//');
    buffer.writeln('// extension LocalizationsExtension on BuildContext {');
    buffer.writeln('//   $className get loc => $className.of(this);');
    buffer.writeln('// }');
    return buffer.toString();
  }

  /// Write extension file to disk (CLI mode).
  Future<void> generateBuildContextExtension(
    String outputDir,
    String className,
  ) async {
    final file = File(path.join(outputDir, 'build_context_extension.dart'));
    await file.writeAsString(generateContent(className));
  }
}
