// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Excel Translator
// 2025-09-04 13:32:55.159338

// Uncomment the lines below to enable BuildContext extension
// This provides easy access like: context.loc.localizations.hello
//
// import 'package:flutter/material.dart';
// import 'generated_localizations.dart';
//
// extension LocalizationsExtension on BuildContext {
//   AppLocalizations get loc => AppLocalizations.of(this);
// }
