import 'dart:async';
import 'dart:io';
import 'package:build/build.dart';
import 'package:yaml/yaml.dart';

import 'src/services/services.dart';
import 'src/parsers/parsers.dart';
import 'src/generators/generators.dart';

/// Build runner builder for Excel Translator.
///
/// Triggered by pubspec.yaml. Also reruns when the excel/csv/ods file changes
/// because reading it via buildStep registers it as an implicit dependency.
///
/// Output directory is resolved in priority order:
///   1. build.yaml options.output_dir (explicit override)
///   2. pubspec.yaml excel_translator.output_dir (default, works for build_runner)
///   3. lib/generated (fallback)
class ExcelTranslatorBuilder implements Builder {
  final _sheetGenerator = SheetClassGenerator();
  final _mainGenerator = MainClassGenerator();
  final _extensionGenerator = ExtensionGenerator();

  final String _outputDir;

  ExcelTranslatorBuilder({String outputDir = 'lib/generated'})
      : _outputDir = outputDir;

  @override
  Map<String, List<String>> get buildExtensions => {
        'pubspec.yaml': [
          '$_outputDir/generated_localizations.dart',
          '$_outputDir/build_context_extension.dart',
        ],
      };

  @override
  Future<void> build(BuildStep buildStep) async {
    final config = await _loadConfig(buildStep);
    if (config == null) {
      log.fine('No excel_translator section in pubspec.yaml — skipping');
      return;
    }

    final excelFile = config['excel_file'] as String?;
    if (excelFile == null) {
      log.warning('excel_translator.excel_file not specified in pubspec.yaml');
      return;
    }

    final excelAsset = AssetId(buildStep.inputId.package, excelFile);
    if (!await buildStep.canRead(excelAsset)) {
      log.warning('Excel file not found: $excelFile');
      return;
    }

    // Reading registers excelAsset as a dependency → builder reruns on change.
    final bytes = await buildStep.readAsBytes(excelAsset);

    final parser = FileParserFactory.createParser(excelFile);
    final sheets = await parser.parseFileFromBytes(
      bytes,
      languageService: LanguageService(
        logInfo: log.info,
        logWarning: log.warning,
      ),
    );

    if (sheets.isEmpty) {
      log.warning('No sheets found in $excelFile');
      return;
    }

    sheets.sort((a, b) => a.name.compareTo(b.name));

    final outputDir = _outputDir;
    final className = config['class_name'] as String? ?? 'AppLocalizations';
    final includeDelegates =
        config['include_flutter_delegates'] as bool? ?? true;

    // ── generated_localizations.dart ─────────────────────────────────────────
    // Inline mode: sheet classes + main class in one file (no per-sheet imports).
    final mainBuffer = StringBuffer();

    // 1. File header + Flutter imports
    mainBuffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    mainBuffer.writeln('// Generated by Excel Translator');
    mainBuffer.writeln('// ignore_for_file: type=lint');
    mainBuffer.writeln();
    if (includeDelegates) {
      mainBuffer.writeln("import 'package:flutter/material.dart';");
      mainBuffer.writeln("import 'package:flutter/cupertino.dart';");
      mainBuffer.writeln(
        "import 'package:excel_translator/excel_translator.dart';",
      );
      mainBuffer.writeln("import 'dart:ui' show PlatformDispatcher;");
      mainBuffer.writeln();
    }

    // 2. Sheet class bodies (inlined — no separate files, no import lines)
    for (final sheet in sheets) {
      mainBuffer.write(_sheetGenerator.generateClassBody(sheet));
      mainBuffer.writeln();
    }

    // 3. Main class + delegate (shares logic with CLI, just no imports block)
    mainBuffer.write(
      _mainGenerator.generateClassAndDelegate(sheets, className, includeDelegates),
    );

    await buildStep.writeAsString(
      AssetId(buildStep.inputId.package,
          '$outputDir/generated_localizations.dart'),
      mainBuffer.toString(),
    );

    // ── build_context_extension.dart ─────────────────────────────────────────
    await buildStep.writeAsString(
      AssetId(buildStep.inputId.package,
          '$outputDir/build_context_extension.dart'),
      _extensionGenerator.generateContent(className),
    );

    log.info('excel_translator: generated localizations from $excelFile');
  }

  Future<Map<String, dynamic>?> _loadConfig(BuildStep buildStep) async {
    final pubspecAsset = AssetId(buildStep.inputId.package, 'pubspec.yaml');
    if (!await buildStep.canRead(pubspecAsset)) return null;

    final content = await buildStep.readAsString(pubspecAsset);
    final yaml = loadYaml(content) as YamlMap;
    final config = yaml['excel_translator'];
    if (config is! YamlMap) return null;

    return config.cast<String, dynamic>();
  }
}

Builder excelTranslatorBuilder(BuilderOptions options) {
  // build.yaml options take priority, then fall back to pubspec.yaml
  final optionsDir = options.config['output_dir'] as String?;
  if (optionsDir != null) {
    return ExcelTranslatorBuilder(outputDir: optionsDir);
  }

  String? pubspecDir;
  try {
    final content = File('pubspec.yaml').readAsStringSync();
    final yaml = loadYaml(content) as YamlMap;
    pubspecDir = yaml['excel_translator']?['output_dir'] as String?;
  } catch (_) {}

  return ExcelTranslatorBuilder(outputDir: pubspecDir ?? 'lib/generated');
}
